CC := g++

ATM : main.o ATM.o User.o Data.o Interface.o others.o
	$(CC) -Istdc++ -o ATM main.o ATM.o User.o Data.o Interface.o others.o

others.o : 
Interface.o : 
User.o :
Data.o :
ATM.o : 
main.o : 

.PHONY : clean
clean: 
	rm *.o
