# Author: Junji Wei
# Date: 2018.3.26
# Version: 1.0
# Makefile for the GuessNumberGame

CC := g++

game : main.o GuessNumber.o
	$(CC) -Istdc++ -o game main.o GuessNumber.o

GuessNumber.o : 
main.o : 

.PHONY : clean
clean: 
	rm *.o
