# Author: Junji Wei
# Date: 2018.4.9
# Version: 0.1
# Makefile

CC := g++

fileManager: main.o FileManager.o
	$(CC) -Istdc++ -o fileManager main.o FileManager.o

FileManager.o:
main.o:

.PYONY: clean
clean:
	rm *.o

